version: '3.8'

services:
  postgres:
    container_name: ${CONTAINER_POSTGRES}
    image: postgres:14.5
    restart: unless-stopped
    environment:
      TZ: Asia/Tehran
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - game-time-data:/var/lib/postgresql/data
    ports:
      - "${PUB_POSTGRES_PORT}:5432"

  app:
    image: golang:1.20.3
    container_name: ${CONTAINER_GO}
    ports:
      - ${PUB_GO_PORT}:8080
    environment:
      TZ: Asia/Tehran
    working_dir: /app
    volumes:
      - ./:/app
      - go-modules:/go/pkg/mod
    entrypoint: /app/docker/app/entrypoint.sh
    depends_on:
      - postgres

volumes:
  go-modules:
  game-time-data:

networks:
  deafult:
    external: true
    name: ${NETWORK_NAME}