version: '3.8'

services:
  app:
    image: golang:1.20.3
    container_name: ${CONTAINER_GO}
    ports:
      - ${PUB_GO_PORT}:8080
    environment:
      TZ: Asia/Tehran
    working_dir: /app
    volumes:
      - ./:/app
      - go-modules:/go/pkg/mod
    entrypoint: /app/docker/app/entrypoint.sh

volumes:
  go-modules:

networks:
  deafult:
    external: true
    name: ${NETWORK_NAME}